apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-example
  labels:
    app: kubernetes-example
spec:
  selector:
    matchLabels:
      app: kubernetes-example
      tier: postgres
  replicas: 3
  template:
    metadata:
      labels:
        app: kubernetes-example
        tier: postgres
    spec:
      containers:
        - image: postgres:12-alpine
          name: postgres
          imagePullPolicy: "IfNotPresent"
          envFrom:
            - secretRef:
                name: postgres-secret

          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-persistent-storage
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: pvc