apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  labels:
    type: local
    app: kubernetes-example
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/kubernetes-example/data"
  persistentVolumeReclaimPolicy: Retain
