apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  labels:
    app: kubernetes-example
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi