apiVersion: v1
kind: Service
metadata:
  name: kubernetes-example
  labels:
    app: kubernetes-example
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: kubernetes-example
    tier: postgres